### ISSUE TITLE
range end index out of range

### ISSUE THREAD

**Issue by infdivzero** [dfyz/osm-renderer#6] opened 2022-07-20 22:38 UTC
Running "cargo run --release --bin renderer city.conf" crashes and spits out:
```
thread 'main' panicked at 'range end index 67004 out of range for slice of length 63744', library/core/src/slice/index.rs:73:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Grabbed an osm.bz2 from https://download.geofabrik.de/north-america/us/us-virgin-islands-latest.osm.bz2, ran "cargo run --release --bin importer us-virgin-islands-latest.osm city.bin," and copied the city.conf from the readme

Compiling on a void linux system using a rustup toolchain. Here's the backtrace:
```
    Finished release [optimized + debuginfo] target(s) in 0.08s
     Running `target/release/renderer city.conf`
thread 'main' panicked at 'range end index 67004 out of range for slice of length 63744', library/core/src/slice/index.rs:73:5
stack backtrace:
   0:     0x55d92c2d7e3d - std::backtrace_rs::backtrace::libunwind::trace::h8e036432725b1c57
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55d92c2d7e3d - std::backtrace_rs::backtrace::trace_unsynchronized::h4f83092254c85869
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d92c2d7e3d - std::sys_common::backtrace::_print_fmt::h9728b5e056a3ece3
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55d92c2d7e3d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h48bb4bd2928827d2
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55d92c2f91ec - core::fmt::write::h909e69a2c24f44cc
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/fmt/mod.rs:1196:17
   5:     0x55d92c2d2dc1 - std::io::Write::write_fmt::h7f4b8ab8af89e9ef
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/io/mod.rs:1654:15
   6:     0x55d92c2d9635 - std::sys_common::backtrace::_print::hff4838ebf14a2171
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55d92c2d9635 - std::sys_common::backtrace::print::h2499280374189ad9
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55d92c2d9635 - std::panicking::default_hook::{{closure}}::h8b270fc55eeb284e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:295:22
   9:     0x55d92c2d92a9 - std::panicking::default_hook::h3217e229d6e9d13c
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:314:9
  10:     0x55d92c2d9c08 - std::panicking::rust_panic_with_hook::h9acb8048b738d2e0
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:698:17
  11:     0x55d92c2d9ab7 - std::panicking::begin_panic_handler::{{closure}}::h70f3b839526af6dc
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:588:13
  12:     0x55d92c2d82f4 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ecf2cee857fbe0a
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55d92c2d97e9 - rust_begin_unwind
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
  14:     0x55d92c24fdc3 - core::panicking::panic_fmt::h9f8393e7fd56d655
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
  15:     0x55d92c2fada6 - core::slice::index::slice_end_index_len_fail_rt::h35f3bf1fe68931f7
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:73:5
  16:     0x55d92c2f2947 - core::ops::function::FnOnce::call_once::h7d45f4dfc649b97a
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
  17:     0x55d92c2f7146 - core::intrinsics::const_eval_select::hc21775f17be7668a
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/intrinsics.rs:2372:5
  18:     0x55d92c24fed6 - core::slice::index::slice_end_index_len_fail::h81337857aea0e15e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:67:9
  19:     0x55d92c2934cd - renderer::geodata::reader::ObjectStorage::from_bytes::h457ac1329dda8072
  20:     0x55d92c2934cd - renderer::geodata::reader::ObjectStorages::from_bytes::h911b389ac5aaf737
                               at /home/user/gitclones/osm-renderer/src/geodata/reader.rs:315:39
  21:     0x55d92c291f11 - renderer::geodata::reader::GeodataReader::load::{{closure}}::h3e874b50a0e8c707
                               at /home/user/gitclones/osm-renderer/src/geodata/reader.rs:52:22
  22:     0x55d92c291f11 - owning_ref::OwningHandle<O,H>::new_with_fn::h699940af1b4b94cd
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/owning_ref-0.4.1/src/lib.rs:898:17
  23:     0x55d92c291f11 - renderer::geodata::reader::GeodataReader::load::h44085b79cad38bc6
                               at /home/user/gitclones/osm-renderer/src/geodata/reader.rs:51:22
  24:     0x55d92c2598a3 - renderer::http_server::run_server::h2d80a0c8ba6ae576
                               at /home/user/gitclones/osm-renderer/src/http_server.rs:44:17
  25:     0x55d92c251a93 - renderer::main::hc277d76c1f900066
                               at /home/user/gitclones/osm-renderer/src/bin/renderer.rs:73:15
  26:     0x55d92c250cd3 - core::ops::function::FnOnce::call_once::hff722edc8b9b6486
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
  27:     0x55d92c250cd3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h028f7d1a11f36e4a
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:122:18
  28:     0x55d92c251049 - std::rt::lang_start::{{closure}}::h853eb92a7e297488
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:145:18
  29:     0x55d92c2cf2ae - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h5f1ba3b861cac230
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:280:13
  30:     0x55d92c2cf2ae - std::panicking::try::do_call::h4febfdb770eca39d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  31:     0x55d92c2cf2ae - std::panicking::try::h8b0eac8a7d726dbf
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  32:     0x55d92c2cf2ae - std::panic::catch_unwind::h11b83c489c0d8394
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  33:     0x55d92c2cf2ae - std::rt::lang_start_internal::{{closure}}::h63502d2988634103
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:48
  34:     0x55d92c2cf2ae - std::panicking::try::do_call::h4be475cff12d2aae
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  35:     0x55d92c2cf2ae - std::panicking::try::h1a3b25b8eaf9ba31
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  36:     0x55d92c2cf2ae - std::panic::catch_unwind::h224588ada67b9b0b
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  37:     0x55d92c2cf2ae - std::rt::lang_start_internal::h2807b375c1959759
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:20
  38:     0x55d92c251fb8 - main
  39:     0x7f9a07f7fe0a - __libc_start_main
                               at /builddir/glibc-2.32/csu/../csu/libc-start.c:314:16
  40:     0x55d92c25006a - _start
                               at /builddir/glibc-2.32/csu/../sysdeps/x86_64/start.S:120
  41:                0x0 - <unknown>
```

**Comment by dfyz** [comment] 2022-07-21 11:32
Thanks for the detailed report! This is definitely a bug, and a nasty one: the importer generated something the renderer couldn't handle at all.

Unfortunately, I can't download the `.osm.bz2` file directly:
![image](https://user-images.githubusercontent.com/42850/180200658-8f654ff4-21dc-4518-af91-f2023ee1765d.png)

I tried the [pbf](http://download.geofabrik.de/north-america/us/us-virgin-islands-latest.osm.pbf) file, and I have a hunch that it's [Antilles](https://www.openstreetmap.org/relation/11946074)/[Lesser Antilles](https://www.openstreetmap.org/relation/13888531) that are causing the problem. They are so large that I can't even import the file locally on my laptop without running out of memory. I strongly suspect that if I *did* have enough memory these relations could cause a `u32` overflow in the generated `.bin` file that would lead to a crash similar to one you're getting.

Could you please try this hacky patch and see if this fixes your error? If yes, the Antilles are indeed problematic, and I can then work on a proper fix. Otherwise, I will investigate further.
```patch
diff --git a/src/geodata/saver.rs b/src/geodata/saver.rs
index cf7d423..5c7b5bb 100644
--- a/src/geodata/saver.rs
+++ b/src/geodata/saver.rs
@@ -179,7 +179,7 @@ fn get_tile_references(entity_storages: &EntityStorages) -> TileIdToReferences {
     }
 
     let polygons = &entity_storages.polygon_storage;
-    for (i, multipolygon) in entity_storages.multipolygon_storage.get_entities().iter().enumerate() {
+    for (i, multipolygon) in entity_storages.multipolygon_storage.get_entities().iter().filter(|x| x.global_id != 11946074 && x.global_id != 13888531).enumerate() {
         let node_ids = multipolygon
             .polygon_ids
             .iter()
```

Also, if you could upload the exact `.osm.bz2` file you were using somewhere, that would be appreciated.

**Comment by infdivzero** [comment] 2022-07-21 14:46
The patch works! Can't download the osm.bz2 either, looks like they took it down. I bunzip2'd it so I had to recom4press it to upload it here: https://tmpfiles.org/dl/352007/us-virgin-islands-latest.osm.gz

**Comment by dfyz** [comment] 2022-07-24 14:50
So, `tmpfiles.org` appears to have already deleted the file, but thankfully `geofabrik.de` put the `.osm.bz2` version back online again and I took a stab at it.

First things first, I think the cleanest way to sidestep the problem is indeed to delete the Antilles relations from the raw data with [osmfilter](https://wiki.openstreetmap.org/wiki/Osmfilter#Download), since these relations don't affect rendering whatsoever.
```
$ ./osmfilter us-virgin-islands-latest.osm --drop="@id=11946074 or @id=13888531" -o=us-virgin-islands-latest-no-antilles.osm
$ cargo run --release --bin importer us-virgin-islands-latest-no-antilles.osm city.bin
[...]
All good
```

You might also want to change the default rendering style to make it more island-friendly:
```patch
diff --git a/mapcss/osmosnimki-minimal.mapcss b/mapcss/osmosnimki-minimal.mapcss
index 94049fc..4c3e773 100644
--- a/mapcss/osmosnimki-minimal.mapcss
+++ b/mapcss/osmosnimki-minimal.mapcss
@@ -1,14 +1,17 @@
+@water: #c4d4f5;
+@background: #fcf8e4;
+
 canvas {
-    fill-color: #fcf8e4;
-    background-color: #fcf8e4;
+    fill-color: @water;
 }
 
 area {
     fill-opacity: 1;
 }
 
-area[natural=coastline] {
-    fill-color: #fcf8e4;
+area[natural=coastline], area[place=island] {
+    fill-position: background;
+    fill-color: @background;
 }
 
 area|z2-[natural=ocean] {
@@ -4636,4 +4639,4 @@ way|z16-["piste:type"=downhill]["piste:difficulty"=freeride] {
     opacity: 0.3;
     width: 4;
     color: yellow;
-}
\ No newline at end of file
+}
```

But anyway, I came up with two ways to import the full file with Antilles successfully:
  * using [an experimental branch](https://github.com/dfyz/osm-renderer/tree/optimize-memory-usage-in-importer) that significantly reduces memory consumption during the import, so that the import succeeds on my 16 GB laptop
  * using a beefy 256 GB machine, where the import consumes a whopping 54 GB (!) of RAM

Surprisingly, in both cases, I actually *didn't* see any errors when running the renderer.

I now strongly suspect that you also got an out of memory error when importing the file (unless you have 54 GB of RAM, of course) and the `city.bin` file was left in an inconsistent state. Could you please check if the importer *didn't* print `All good` at the very end and/or if there were `dmesg` entries that look like `Out of memory: Killed process 94574 (importer)` after the import?

If so, that's still a nasty bug on my side that I should fix, probably by first writing the data to a temporary file, and then making an atomic rename to the final file.

**Comment by infdivzero** [comment] 2022-07-24 18:49
The importer gets SIGKILLed after the internal format conversion, doesn't print anything else after that. dmesg shows the out of memory error

**Comment by dfyz** [comment] 2022-07-24 23:43
Okay, to sum it up: the original error the issue started from happens because the importer generated `city.bin` on the file system even though the import actually failed. The renderer then crashed when loading said `city.bin` because it trusts the importer to generate a valid file. 

I just pushed 89c10decf727a48109356fc8522e5d7e4382a410, which ensures there will be no `city.bin` on the disk if anything went wrong during the import.

In the future, the renderer should probably learn to detect when the imported file is broken and give better error messages, but for now I'd rather keep the loading code as simple as possible. So with that in mind, I think I'm going to close this issue.

**Closed by dfyz** 2022-07-24 23:43 UTC
