### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by Aruee** [dfyz/osm-renderer#4] opened 2022-03-11 11:12 UTC
Hey there! Just wanted to try the renderer but I can't even build it:

```
$ cargo run --release --bin importer map.osm out.bin
   Compiling renderer v1.0.0 (/home/stop_ja/Quellcode/thirdParty/osm-renderer)
error[E0308]: mismatched types
  --> src/draw/icon.rs:20:13
   |
20 |         let (info, mut reader) = decoder.read_info().context("Icon is not a valid PNG file")?;
   |             ^^^^^^^^^^^^^^^^^^   ------------------------------------------------------------ this expression has type `Reader<File>`
   |             |
   |             expected struct `Reader`, found tuple
   |
   = note: expected struct `Reader<File>`
               found tuple `(_, _)`

error[E0599]: no variant or associated item named `RGB` found for enum `ColorType` in the current scope
  --> src/draw/icon.rs:27:32
   |
27 |                     ColorType::RGB => (row[idx], row[idx + 1], row[idx + 2], u8::max_value(), 3),
   |                                ^^^
   |                                |
   |                                variant or associated item not found in `ColorType`
   |                                help: there is a variant with a similar name: `Rgb`

error[E0599]: no variant or associated item named `RGBA` found for enum `ColorType` in the current scope
  --> src/draw/icon.rs:28:32
   |
28 |                     ColorType::RGBA => (row[idx], row[idx + 1], row[idx + 2], row[idx + 3], 4),
   |                                ^^^^
   |                                |
   |                                variant or associated item not found in `ColorType`
   |                                help: there is a variant with a similar name: `Rgba`

error[E0599]: no variant or associated item named `RGB` found for enum `ColorType` in the current scope
 --> src/draw/png_writer.rs:8:42
  |
8 |         png_encoder.set_color(ColorType::RGB);
  |                                          ^^^
  |                                          |
  |                                          variant or associated item not found in `ColorType`
  |                                          help: there is a variant with a similar name: `Rgb`

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `renderer` due to 4 previous errors

```

Am I missing something? Thanks in advance for any help.

**Comment by dfyz** [comment] 2022-03-11 12:52
Hi! These compile errors appear to come from building the renderer with one of the newer versions of the `png` crate (`0.17.*`, I guess). This is really weird, since I currently have the `png` version pinned to `0.16.8` in [Cargo.lock](https://github.com/dfyz/osm-renderer/blob/master/Cargo.lock#L246).

To double check I didn't mess anything up, I just did a clean install of Rust and a clean checkout of the renderer on a new machine, but everything works as expected for me:
  * when I run `cargo run --release --bin importer map.osm out.bin` on a clean checkout, cargo uses `png 0.16.8`, and the importer builds and runs just fine.
  * if I do `cargo update` before building, `png` gets updated to `0.17.5`, and then I get compile errors similar to yours.

Could you please clarify what exactly you did before running `cargo run --release --bin importer map.osm out.bin` so that I can reproduce the build errors?

By the way, I'm also planning to update the code to work with `0.17.*`, but some of the tests started failing when I fix the compile errors, so it might take a while.

**Comment by dfyz** [comment] 2022-03-13 00:39
> By the way, I'm also planning to update the code to work with 0.17.*

I just updated the code to work with the latest version of `png` in https://github.com/dfyz/osm-renderer/commit/4f386f7eb7290cc0ba85bb31f8166e8dc917931d. Are you still getting build errors with the latest `master`?

**Comment by dfyz** [comment] 2022-07-24 23:47
Okay, I'm pretty sure this should be fixed now, so I am going to close this issue. Feel free to re-open if you're still having build problems.

**Closed by dfyz** 2022-07-24 23:47 UTC
